// <auto-generated />
namespace ArkBarGarage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kippo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kippo));
        
        string IMigrationMetadata.Id
        {
            get { return "201902031219288_kippo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
